# Generated by Django 5.1.1 on 2024-10-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='cantidad',
        ),
    ]
