# Generated by Django 5.1.1 on 2024-10-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_carritoproducto_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoproducto',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoProducto',
        ),
    ]
